### ISSUE TITLE
std::to_string not available

### ISSUE THREAD

**Issue by wassfila** [HomeSmartMesh/IoT_Frameworks#3]
serial.cpp:128:20: error: 'to_string' is not a member of 'std'
strlog+="error "+std::to_string(errno)+" opening "+port_name+" : "+strerror(errno);

**Comment by redotics** [comment]
For info: std::to_string has been introduced in <string> since C++11 which is a standard that has to be activated during compilation "g++ -std=c++11 ..."

**Comment by wassfila** [comment]
Yeah right, I did not made the link, even after adding the flag for another purpose...
Thanks !!!!
